# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# NeoForge Properties
# check these on https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.40-beta

# Mod Properties
mod_id=worldpainter
mod_name=World Painter
mod_license=CC0-1.0
mod_version=1.2.0
mod_group_id=com.daniel.worldpainter
mod_authors=Daniel
