# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Babric (Fabric for Beta 1.7.3) properties, from the Babric example mod:
# https://github.com/calmilamsy/stationapi-example-mod
minecraft_version=b1.7.3
biny_mappings=b1.7.3+4cbd9c8
loader_version=0.19.5
loom_version=1.17.20
babric_loom_version=1.17.4

# Mod Properties
mod_version=1.2.0
maven_group=com.daniel.worldpainter
